// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqhhqibvrlhpiqdwfngi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxaGhxaWJ2cmxocGlxZHdmbmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDQ2ODEsImV4cCI6MjA2MTEyMDY4MX0.PsPowk534ni2Jdcv5iojS7ZKZ84BnLRk52-FU6vmQRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);